from fpdf import FPDF
from datetime import datetime

class CreditMemoGenerator(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()
        self.set_font("Arial", size=12)

    def header(self):
        # 银行级页眉
        self.set_font("Arial", 'B', 10)
        self.set_text_color(100, 100, 100) 
        self.cell(0, 10, "CONFIDENTIAL | INTERNAL CREDIT COMMITTEE USE ONLY", 0, 1, 'R')
        self.ln(5)

    def footer(self):
        # 页脚 + 免责声明
        self.set_y(-25)
        self.set_font("Arial", 'I', 6) # 字体极小
        self.set_text_color(150)
        disclaimer = (
            "DISCLAIMER: This report is a decision support tool generated by the Cross-Border Credit Lens system. "
            "MAS Green Taxonomy: Indicative alignment based on publicly available data, subject to external assurance. "
            "Stress test conducted at subsidiary level only; group-level liquidity not modelled."
        )
        self.multi_cell(0, 3, disclaimer, align='C')
        
        self.set_y(-10)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.set_font("Arial", 'I', 7)
        self.cell(0, 10, f'Generated by Risk Engine V32.1 | {timestamp} | Page {self.page_no()}', 0, 0, 'C')

    def section_title(self, title):
        self.ln(5)
        self.set_font("Arial", 'B', 11)
        self.set_fill_color(240, 240, 240) # 浅灰底色
        self.set_text_color(0, 51, 102) # SCB Blue
        self.cell(0, 8, f"  {title}", 0, 1, 'L', fill=True)
        self.ln(3)

    def draw_conclusion_box(self, text):
        # Credit Conclusion Box (一句话总结框)
        self.set_fill_color(245, 245, 245) 
        self.set_draw_color(200, 200, 200) 
        self.set_font("Arial", 'I', 9) 
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, f"Overall Credit View: {text}", 1, 'L', True)
        self.ln(3)

    def add_version_log(self):
        # Version Control Log
        self.ln(10)
        self.set_font("Courier", '', 7) 
        self.set_text_color(100)
        self.cell(0, 4, "--- MLOps Model Governance Log ---", 0, 1)
        self.cell(0, 4, "Model Version: V32.1 (Production)", 0, 1)
        self.cell(0, 4, "> Removed proprietary trading signals per compliance requirement", 0, 1)
        self.cell(0, 4, "> Reframed output as credit decision support (Basel III aligned)", 0, 1)
        self.cell(0, 4, "> Added geopolitical compliance overlay (UFLPA/Tariff)", 0, 1)

    def generate_report(self, data, filename="Credit_Committee_Memo.pdf"):
        # ============================================
        # 1. 顶部信息 (已修复溢出问题)
        # ============================================
        self.set_font("Arial", 'B', 16)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, "CREDIT APPROVAL MEMO (CAM)", 0, 1, 'C')
        self.ln(2)

        # Risk Owner 字段
        self.set_font("Arial", 'B', 8)
        self.set_text_color(0, 51, 102)
        self.cell(0, 5, "Primary Risk Owner: Credit Risk (SG HQ) | Secondary Review: Compliance / Trade Finance", 0, 1, 'C')
        self.set_text_color(0)
        self.ln(5)

        self.set_font("Arial", size=10)
        line_height = 7 # 稍微调高行高，更美观
        
        # --- [这里是修复的核心逻辑：三行布局] ---
        
        # Row 1: Borrower (占满整行)
        self.set_font("Arial", 'B', 10); self.cell(35, line_height, "Borrower:", 0)
        self.set_font("Arial", '', 10);  self.cell(0, line_height, data['borrower'], 0, 1)
        
        # Row 2: Guarantor (占满整行)
        self.set_font("Arial", 'B', 10); self.cell(35, line_height, "Guarantor:", 0)
        self.set_font("Arial", '', 10);  self.cell(0, line_height, data['guarantor'], 0, 1)
        
        # Row 3: Facility (左) + Amount (右)
        # 左边给 95mm (35标签 + 60内容)
        self.set_font("Arial", 'B', 10); self.cell(35, line_height, "Facility:", 0)
        self.set_font("Arial", '', 10);  self.cell(60, line_height, data['facility'], 0)
        
        # 右边占满剩余
        self.set_font("Arial", 'B', 10); self.cell(25, line_height, "Amount:", 0)
        self.set_font("Arial", '', 10);  self.cell(0, line_height, data['amount'], 0, 1)

        self.ln(3)

        # ============================================
        # 2. Executive Summary
        # ============================================
        self.section_title("1. EXECUTIVE SUMMARY & RECOMMENDATION")
        
        self.set_font("Arial", 'B', 11)
        self.cell(55, 10, "INDICATIVE DECISION:", 0)
        
        if "APPROVE" in data['recommendation'].upper():
            self.set_text_color(40, 167, 69) 
        else:
            self.set_text_color(220, 53, 69) 
            
        self.cell(0, 10, data['recommendation'], 0, 1)
        self.set_text_color(0)
        
        self.set_font("Arial", 'B', 9)
        self.cell(0, 6, "Conditions / Rationale:", 0, 1)
        self.set_font("Arial", '', 9)
        self.multi_cell(0, 5, data['rationale'])
        self.ln(4)

        # 结论框
        self.draw_conclusion_box(data['credit_view'])

        # ============================================
        # 3. Risk Dashboard
        # ============================================
        self.section_title("2. INTEGRATED RISK DASHBOARD")
        
        # Header
        self.set_font("Arial", 'B', 8)
        self.set_fill_color(250)
        self.cell(35, 7, "Risk Dimension", 1, 0, 'C', fill=True)
        self.cell(30, 7, "Status", 1, 0, 'C', fill=True) 
        self.cell(40, 7, "Key Metric", 1, 0, 'C', fill=True)
        self.cell(85, 7, "Risk Analyst Comment", 1, 1, 'C', fill=True)
        
        self.set_font("Arial", '', 7.5) 
        for item in data['risk_items']:
            self.cell(35, 7, item['dim'], 1)
            
            # Status Logic
            status_text = item['status'] 
            fill_color = (200, 200, 200)

            if "Low" in item['status']: 
                status_text = "Low (Acceptable)"
                fill_color = (40, 167, 69)
            elif "High" in item['status']: 
                status_text = "High (Restrictive)"
                fill_color = (220, 53, 69)
            else: 
                status_text = "Med (Monitor)"
                fill_color = (255, 193, 7)
            
            self.set_fill_color(*fill_color)
            x, y = self.get_x(), self.get_y()
            self.rect(x, y, 30, 7, 'F') 
            
            if "Med" in status_text: self.set_text_color(0)
            else: self.set_text_color(255)
            
            self.cell(30, 7, status_text, 1, 0, 'C')
            self.set_text_color(0) 
            
            self.cell(40, 7, item['metric'], 1)
            self.cell(85, 7, item['comment'], 1, 1)

        # ============================================
        # 4. Agent Insights
        # ============================================
        self.section_title("3. COMPLIANCE & GEOPOLITICS COPILOT")
        for agent in data['agent_insights']:
            self.set_font("Arial", 'B', 9)
            self.cell(5, 5, "-", 0)
            self.cell(0, 5, agent['title'], 0, 1)
            self.set_font("Arial", '', 8)
            self.set_text_color(80)
            self.multi_cell(0, 4, "   " + agent['detail'])
            self.set_text_color(0)
            self.ln(2)

        # ============================================
        # 5. Stress Test
        # ============================================
        self.section_title("4. SCENARIO STRESS TEST")
        
        self.set_font("Arial", 'I', 8)
        self.set_text_color(100)
        self.cell(0, 5, "Scope: Stress test conducted at subsidiary level only; group-level liquidity not modelled.", 0, 1)
        self.set_text_color(0)
        self.ln(1)

        self.set_font("Arial", 'B', 9)
        self.cell(0, 6, f"Stress Scenario: {data['stress_scenario']}", 0, 1)
        
        self.set_font("Arial", '', 9)
        self.ln(1)
        for outcome in data['stress_outcomes']:
            self.cell(5, 5, ">>", 0) 
            self.cell(0, 5, outcome, 0, 1)
        self.ln(2)
        
        self.set_font("Arial", 'B', 9)
        self.set_text_color(180, 0, 0)
        self.cell(0, 6, "REQUIRED MITIGATION:", 0, 1)
        self.set_text_color(0)
        self.set_font("Arial", '', 9)
        self.multi_cell(0, 5, data['mitigation'])

        # Log
        self.add_version_log()

        self.output(filename)
        print(f"✅ Credit Memo Generated: {filename}")

# ==========================================
# 模拟数据输入 (用于测试排版)
# ==========================================
if __name__ == "__main__":
    mock_data = {
        "borrower": "Longi Green Energy Technology (Vietnam) Co., Ltd.", # 故意写长一点测试
        "guarantor": "Longi Green Energy (SH.601012) - HQ Guarantee",
        "facility": "Working Capital Loan (Cross-Border)",
        "amount": "USD 50,000,000",
        
        "recommendation": "CONDITIONAL APPROVAL (Indicative)", 
        "rationale": "Subject to further site verification. \n1. Corporate Guarantee required.\n2. 80% SINOSURE coverage on US receivables.",
        
        "credit_view": "Parent-supported structure mitigates subsidiary liquidity risk. However, high exposure to US trade policy warrants close monitoring.",

        "risk_items": [
            {"dim": "Financials", "status": "Low", "metric": "Score 780 (AA)", "comment": "Strong parent support."},
            {"dim": "Market Risk", "status": "Medium", "metric": "Implied Prem. +150bps", "comment": "Market pricing mismatch."}, 
            {"dim": "Geopolitics", "status": "High", "metric": "Tariff Exp 45%", "comment": "High sensitivity to US probe."}
        ],
        
        "agent_insights": [
            {"title": "US Sanctions Check", "detail": "CLEARED. No hits in UFLPA list."},
            {"title": "MAS Green Taxonomy", "detail": "ALIGNED (Proxy). Matches Tier-1 Renewable Mfg criteria."} 
        ],
        
        "stress_scenario": "US Tariff +50%",
        
        "stress_outcomes": [
            "DSCR: 1.5x -> 0.8x (Below Covenant)",
            "Cash Flow: Positive -> Negative",
            "Risk Status: Breach without parent support"
        ],
        
        "mitigation": "Parent guarantee triggered at DSCR < 1.0x."
    }

    pdf = CreditMemoGenerator()
    pdf.generate_report(mock_data)
